### ISSUE TITLE
slug input

### ISSUE THREAD

**Issue by 3052** [andreasots/vhx-downloader#1]
is it possible to offer slug input in addition to series ID?

~~~
criterionchannel.com/my-dinner-with-andre -> my-dinner-with-andre
~~~

https://github.com/andreasots/vhx-downloader/blob/eae8b73f823f7bfac28e4c261d885169eda299fa/vhx-downloader.py#L15

**Comment by andreasots** [comment]
This does not seem to be supported by the API this script is using.

**Comment by 3052** [comment]
found it

```
GET https://api.vhx.com/videos/my-dinner-with-andre?url=my-dinner-with-andre HTTP/2.0
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2YmZlZmMzNGIyNTdhYTE4Y2E2...
```

**Comment by andreasots** [comment]
That endpoint only works for single videos and not an entire series.

**Comment by 3052** [comment]
`/collections/${slug}/items?site_id=${process.env.SITE_ID}` should also work
